name: release
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v7.0.1
        with:
          fetch-depth: 0
      - name: Add variables to environment file
        run: cat ".github/env" >> "$GITHUB_ENV"
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # pin@7.0.0
        with:
          go-version: "${{ env.GOLANG_VERSION }}"
          check-latest: true
      - name: Run unit tests
        run: make test-coverage
      - name: Build Helm binaries
        run: |
          set -eu -o pipefail

          make build-cross VERSION="${{ github.ref_name }}"
          make dist checksum VERSION="${{ github.ref_name }}"
      - name: Create GitHub Release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eu -o pipefail

          gh release create "${{ github.ref_name }}" \
            _dist/*.tar.gz _dist/*.zip _dist/*.sha256 _dist/*.sha256sum \
            --title "${{ github.ref_name }}" \
            --generate-notes
